services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v5.0.0
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/openapi.yaml
      BASE_URL: /
    volumes:
      - "./spec/openapi.yaml:/app/openapi.yaml:ro
