// <auto-generated>
/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Dev.ABGEO.UBill.SDK.Client;

namespace Dev.ABGEO.UBill.SDK.Model
{
    /// <summary>
    /// CreateBrandNamePayload
    /// </summary>
    public partial class CreateBrandNamePayload : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateBrandNamePayload" /> class.
        /// </summary>
        /// <param name="brandName">brandName</param>
        [JsonConstructor]
        public CreateBrandNamePayload(string brandName)
        {
            BrandName = brandName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets BrandName
        /// </summary>
        /* <example>ubill-info</example> */
        [JsonPropertyName("brandName")]
        public string BrandName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateBrandNamePayload {\n");
            sb.Append("  BrandName: ").Append(BrandName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="CreateBrandNamePayload" />
    /// </summary>
    public class CreateBrandNamePayloadJsonConverter : JsonConverter<CreateBrandNamePayload>
    {
        /// <summary>
        /// Deserializes json to <see cref="CreateBrandNamePayload" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override CreateBrandNamePayload Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> brandName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "brandName":
                            brandName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!brandName.IsSet)
                throw new ArgumentException("Property is required for class CreateBrandNamePayload.", nameof(brandName));

            if (brandName.IsSet && brandName.Value == null)
                throw new ArgumentNullException(nameof(brandName), "Property is not nullable for class CreateBrandNamePayload.");

            return new CreateBrandNamePayload(brandName.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="CreateBrandNamePayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createBrandNamePayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, CreateBrandNamePayload createBrandNamePayload, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, createBrandNamePayload, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="CreateBrandNamePayload" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="createBrandNamePayload"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, CreateBrandNamePayload createBrandNamePayload, JsonSerializerOptions jsonSerializerOptions)
        {
            if (createBrandNamePayload.BrandName == null)
                throw new ArgumentNullException(nameof(createBrandNamePayload.BrandName), "Property is required for class CreateBrandNamePayload.");

            writer.WriteString("brandName", createBrandNamePayload.BrandName);
        }
    }
}
