// <auto-generated>
/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Dev.ABGEO.UBill.SDK.Client;

namespace Dev.ABGEO.UBill.SDK.Model
{
    /// <summary>
    /// DeliveryReportItem
    /// </summary>
    public partial class DeliveryReportItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeliveryReportItem" /> class.
        /// </summary>
        /// <param name="number">number</param>
        /// <param name="statusID">statusID</param>
        [JsonConstructor]
        public DeliveryReportItem(Option<string?> number = default, Option<string?> statusID = default)
        {
            NumberOption = number;
            StatusIDOption = statusID;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Number
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NumberOption { get; private set; }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        /* <example>995511194241</example> */
        [JsonPropertyName("number")]
        public string? Number { get { return this.NumberOption; } set { this.NumberOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusID
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> StatusIDOption { get; private set; }

        /// <summary>
        /// Gets or Sets StatusID
        /// </summary>
        /* <example>1</example> */
        [JsonPropertyName("statusID")]
        public string? StatusID { get { return this.StatusIDOption; } set { this.StatusIDOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeliveryReportItem {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  StatusID: ").Append(StatusID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DeliveryReportItem" />
    /// </summary>
    public class DeliveryReportItemJsonConverter : JsonConverter<DeliveryReportItem>
    {
        /// <summary>
        /// Deserializes json to <see cref="DeliveryReportItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DeliveryReportItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> number = default;
            Option<string?> statusID = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "number":
                            number = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "statusID":
                            statusID = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (number.IsSet && number.Value == null)
                throw new ArgumentNullException(nameof(number), "Property is not nullable for class DeliveryReportItem.");

            if (statusID.IsSet && statusID.Value == null)
                throw new ArgumentNullException(nameof(statusID), "Property is not nullable for class DeliveryReportItem.");

            return new DeliveryReportItem(number, statusID);
        }

        /// <summary>
        /// Serializes a <see cref="DeliveryReportItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="deliveryReportItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DeliveryReportItem deliveryReportItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, deliveryReportItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DeliveryReportItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="deliveryReportItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DeliveryReportItem deliveryReportItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (deliveryReportItem.NumberOption.IsSet && deliveryReportItem.Number == null)
                throw new ArgumentNullException(nameof(deliveryReportItem.Number), "Property is required for class DeliveryReportItem.");

            if (deliveryReportItem.StatusIDOption.IsSet && deliveryReportItem.StatusID == null)
                throw new ArgumentNullException(nameof(deliveryReportItem.StatusID), "Property is required for class DeliveryReportItem.");

            if (deliveryReportItem.NumberOption.IsSet)
                writer.WriteString("number", deliveryReportItem.Number);

            if (deliveryReportItem.StatusIDOption.IsSet)
                writer.WriteString("statusID", deliveryReportItem.StatusID);
        }
    }
}
