// <auto-generated>
/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Dev.ABGEO.UBill.SDK.Client;

namespace Dev.ABGEO.UBill.SDK.Model
{
    /// <summary>
    /// SendSMSResponse
    /// </summary>
    public partial class SendSMSResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendSMSResponse" /> class.
        /// </summary>
        /// <param name="statusID">Response status code</param>
        /// <param name="message">Human-readable response message</param>
        /// <param name="smsID">smsID</param>
        [JsonConstructor]
        public SendSMSResponse(long statusID, Option<string?> message = default, Option<string?> smsID = default)
        {
            StatusID = statusID;
            MessageOption = message;
            SmsIDOption = smsID;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Response status code
        /// </summary>
        /// <value>Response status code</value>
        /* <example>0</example> */
        [JsonPropertyName("statusID")]
        public long StatusID { get; set; }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Human-readable response message
        /// </summary>
        /// <value>Human-readable response message</value>
        /* <example>Success</example> */
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of SmsID
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SmsIDOption { get; private set; }

        /// <summary>
        /// Gets or Sets SmsID
        /// </summary>
        /* <example>100</example> */
        [JsonPropertyName("smsID")]
        public string? SmsID { get { return this.SmsIDOption; } set { this.SmsIDOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendSMSResponse {\n");
            sb.Append("  StatusID: ").Append(StatusID).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  SmsID: ").Append(SmsID).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendSMSResponse" />
    /// </summary>
    public class SendSMSResponseJsonConverter : JsonConverter<SendSMSResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendSMSResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendSMSResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> statusID = default;
            Option<string?> message = default;
            Option<string?> smsID = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "statusID":
                            statusID = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "smsID":
                            smsID = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!statusID.IsSet)
                throw new ArgumentException("Property is required for class SendSMSResponse.", nameof(statusID));

            if (statusID.IsSet && statusID.Value == null)
                throw new ArgumentNullException(nameof(statusID), "Property is not nullable for class SendSMSResponse.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class SendSMSResponse.");

            if (smsID.IsSet && smsID.Value == null)
                throw new ArgumentNullException(nameof(smsID), "Property is not nullable for class SendSMSResponse.");

            return new SendSMSResponse(statusID.Value!.Value!, message, smsID);
        }

        /// <summary>
        /// Serializes a <see cref="SendSMSResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendSMSResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendSMSResponse sendSMSResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendSMSResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendSMSResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendSMSResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendSMSResponse sendSMSResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendSMSResponse.MessageOption.IsSet && sendSMSResponse.Message == null)
                throw new ArgumentNullException(nameof(sendSMSResponse.Message), "Property is required for class SendSMSResponse.");

            if (sendSMSResponse.SmsIDOption.IsSet && sendSMSResponse.SmsID == null)
                throw new ArgumentNullException(nameof(sendSMSResponse.SmsID), "Property is required for class SendSMSResponse.");

            writer.WriteNumber("statusID", sendSMSResponse.StatusID);

            if (sendSMSResponse.MessageOption.IsSet)
                writer.WriteString("message", sendSMSResponse.Message);

            if (sendSMSResponse.SmsIDOption.IsSet)
                writer.WriteString("smsID", sendSMSResponse.SmsID);
        }
    }
}
