/*
UBill API

UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.

API version: 2.1.7
Contact: info@ubill.ge
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ubill

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the BrandNamesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrandNamesResponse{}

// BrandNamesResponse struct for BrandNamesResponse
type BrandNamesResponse struct {
	StatusID int64       `json:"statusID"`
	Brands   []BrandName `json:"brands,omitempty"`
}

type _BrandNamesResponse BrandNamesResponse

// NewBrandNamesResponse instantiates a new BrandNamesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandNamesResponse(statusID int64) *BrandNamesResponse {
	this := BrandNamesResponse{}
	this.StatusID = statusID
	return &this
}

// NewBrandNamesResponseWithDefaults instantiates a new BrandNamesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandNamesResponseWithDefaults() *BrandNamesResponse {
	this := BrandNamesResponse{}
	return &this
}

// GetStatusID returns the StatusID field value
func (o *BrandNamesResponse) GetStatusID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StatusID
}

// GetStatusIDOk returns a tuple with the StatusID field value
// and a boolean to check if the value has been set.
func (o *BrandNamesResponse) GetStatusIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StatusID, true
}

// SetStatusID sets field value
func (o *BrandNamesResponse) SetStatusID(v int64) {
	o.StatusID = v
}

// GetBrands returns the Brands field value if set, zero value otherwise.
func (o *BrandNamesResponse) GetBrands() []BrandName {
	if o == nil || IsNil(o.Brands) {
		var ret []BrandName
		return ret
	}
	return o.Brands
}

// GetBrandsOk returns a tuple with the Brands field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandNamesResponse) GetBrandsOk() ([]BrandName, bool) {
	if o == nil || IsNil(o.Brands) {
		return nil, false
	}
	return o.Brands, true
}

// HasBrands returns a boolean if a field has been set.
func (o *BrandNamesResponse) HasBrands() bool {
	if o != nil && !IsNil(o.Brands) {
		return true
	}

	return false
}

// SetBrands gets a reference to the given []BrandName and assigns it to the Brands field.
func (o *BrandNamesResponse) SetBrands(v []BrandName) {
	o.Brands = v
}

func (o BrandNamesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrandNamesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["statusID"] = o.StatusID
	if !IsNil(o.Brands) {
		toSerialize["brands"] = o.Brands
	}
	return toSerialize, nil
}

func (o *BrandNamesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"statusID",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBrandNamesResponse := _BrandNamesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBrandNamesResponse)

	if err != nil {
		return err
	}

	*o = BrandNamesResponse(varBrandNamesResponse)

	return err
}

type NullableBrandNamesResponse struct {
	value *BrandNamesResponse
	isSet bool
}

func (v NullableBrandNamesResponse) Get() *BrandNamesResponse {
	return v.value
}

func (v *NullableBrandNamesResponse) Set(val *BrandNamesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandNamesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandNamesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandNamesResponse(val *BrandNamesResponse) *NullableBrandNamesResponse {
	return &NullableBrandNamesResponse{value: val, isSet: true}
}

func (v NullableBrandNamesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandNamesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
