/*
UBill API

UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.

API version: 2.1.7
Contact: info@ubill.ge
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ubill

import (
	"encoding/json"
)

// checks if the BrandName type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BrandName{}

// BrandName struct for BrandName
type BrandName struct {
	Id         *string `json:"id,omitempty"`
	Name       *string `json:"name,omitempty"`
	Authorized *string `json:"authorized,omitempty"`
	CreatedAt  *string `json:"createdAt,omitempty"`
}

// NewBrandName instantiates a new BrandName object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBrandName() *BrandName {
	this := BrandName{}
	return &this
}

// NewBrandNameWithDefaults instantiates a new BrandName object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBrandNameWithDefaults() *BrandName {
	this := BrandName{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BrandName) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandName) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BrandName) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BrandName) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BrandName) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandName) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BrandName) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BrandName) SetName(v string) {
	o.Name = &v
}

// GetAuthorized returns the Authorized field value if set, zero value otherwise.
func (o *BrandName) GetAuthorized() string {
	if o == nil || IsNil(o.Authorized) {
		var ret string
		return ret
	}
	return *o.Authorized
}

// GetAuthorizedOk returns a tuple with the Authorized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandName) GetAuthorizedOk() (*string, bool) {
	if o == nil || IsNil(o.Authorized) {
		return nil, false
	}
	return o.Authorized, true
}

// HasAuthorized returns a boolean if a field has been set.
func (o *BrandName) HasAuthorized() bool {
	if o != nil && !IsNil(o.Authorized) {
		return true
	}

	return false
}

// SetAuthorized gets a reference to the given string and assigns it to the Authorized field.
func (o *BrandName) SetAuthorized(v string) {
	o.Authorized = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *BrandName) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BrandName) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *BrandName) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *BrandName) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o BrandName) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BrandName) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Authorized) {
		toSerialize["authorized"] = o.Authorized
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableBrandName struct {
	value *BrandName
	isSet bool
}

func (v NullableBrandName) Get() *BrandName {
	return v.value
}

func (v *NullableBrandName) Set(val *BrandName) {
	v.value = val
	v.isSet = true
}

func (v NullableBrandName) IsSet() bool {
	return v.isSet
}

func (v *NullableBrandName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBrandName(val *BrandName) *NullableBrandName {
	return &NullableBrandName{value: val, isSet: true}
}

func (v NullableBrandName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBrandName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
