/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dev.ABGEO.UBill.SDK.Model;
using Dev.ABGEO.UBill.SDK.Client;
using System.Reflection;

namespace Dev.ABGEO.UBill.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing BrandName
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BrandNameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BrandName
        //private BrandName instance;

        public BrandNameTests()
        {
            // TODO uncomment below to create an instance of BrandName
            //instance = new BrandName();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrandName
        /// </summary>
        [Fact]
        public void BrandNameInstanceTest()
        {
            // TODO uncomment below to test "IsType" BrandName
            //Assert.IsType<BrandName>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Authorized'
        /// </summary>
        [Fact]
        public void AuthorizedTest()
        {
            // TODO unit test for the property 'Authorized'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
