/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dev.ABGEO.UBill.SDK.Model;
using Dev.ABGEO.UBill.SDK.Client;
using System.Reflection;

namespace Dev.ABGEO.UBill.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing DeliveryReportItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliveryReportItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeliveryReportItem
        //private DeliveryReportItem instance;

        public DeliveryReportItemTests()
        {
            // TODO uncomment below to create an instance of DeliveryReportItem
            //instance = new DeliveryReportItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeliveryReportItem
        /// </summary>
        [Fact]
        public void DeliveryReportItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeliveryReportItem
            //Assert.IsType<DeliveryReportItem>(instance);
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Fact]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }

        /// <summary>
        /// Test the property 'StatusID'
        /// </summary>
        [Fact]
        public void StatusIDTest()
        {
            // TODO unit test for the property 'StatusID'
        }
    }
}
