/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dev.ABGEO.UBill.SDK.Model;
using Dev.ABGEO.UBill.SDK.Client;
using System.Reflection;

namespace Dev.ABGEO.UBill.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing SMSBalanceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SMSBalanceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SMSBalanceResponse
        //private SMSBalanceResponse instance;

        public SMSBalanceResponseTests()
        {
            // TODO uncomment below to create an instance of SMSBalanceResponse
            //instance = new SMSBalanceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SMSBalanceResponse
        /// </summary>
        [Fact]
        public void SMSBalanceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" SMSBalanceResponse
            //Assert.IsType<SMSBalanceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'StatusID'
        /// </summary>
        [Fact]
        public void StatusIDTest()
        {
            // TODO unit test for the property 'StatusID'
        }

        /// <summary>
        /// Test the property 'Sms'
        /// </summary>
        [Fact]
        public void SmsTest()
        {
            // TODO unit test for the property 'Sms'
        }
    }
}
