/*
 * UBill API
 *
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Dev.ABGEO.UBill.SDK.Model;
using Dev.ABGEO.UBill.SDK.Client;
using System.Reflection;

namespace Dev.ABGEO.UBill.SDK.Test.Model
{
    /// <summary>
    ///  Class for testing SMSPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SMSPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SMSPayload
        //private SMSPayload instance;

        public SMSPayloadTests()
        {
            // TODO uncomment below to create an instance of SMSPayload
            //instance = new SMSPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SMSPayload
        /// </summary>
        [Fact]
        public void SMSPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" SMSPayload
            //Assert.IsType<SMSPayload>(instance);
        }

        /// <summary>
        /// Test the property 'BrandID'
        /// </summary>
        [Fact]
        public void BrandIDTest()
        {
            // TODO unit test for the property 'BrandID'
        }

        /// <summary>
        /// Test the property 'Numbers'
        /// </summary>
        [Fact]
        public void NumbersTest()
        {
            // TODO unit test for the property 'Numbers'
        }

        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }

        /// <summary>
        /// Test the property 'StopList'
        /// </summary>
        [Fact]
        public void StopListTest()
        {
            // TODO unit test for the property 'StopList'
        }
    }
}
